# Justfile for managing infrastructure with Tofu

# Initilize the project setup
@init:
  echo "🚧 Initializing project setup..."
  tofu init

# Plan infrastructure changes
@plan:
  echo "🛠️ Planning infrastructure changes..."
  tofu plan -parallelism=50

# Apply infrastructure changes
@apply:
  echo "✅ Apply infrastructure changes..."
  tofu apply -auto-approve -parallelism=50

# Reformat code
@format:
  echo "🎨 Formatting code..."
  tofu fmt

# Reformat code
@fmt: format

# Check code formatting
@check-format:
  echo "🔍 Checking code formatting..."
  tofu fmt --check
